version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - wget https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip
      - unzip terraform_1.0.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      
  build:
    commands:

      - terraform --version
      - terraform -chdir="./ecs" init
      - terraform -chdir="./ecs" validate     
      - terraform -chdir="./ecs" apply --auto-approve
